### ISSUE TITLE
Failed to load Font file: FrankBold50_A8_icons.fnt

### ISSUE THREAD

**Issue by umairnow** [wrld3d/ios-api-example#2]
I am using swift and cocoapods to use this sdk, I have just written a small piece of code to load map. When I run the application I get the following error:
Eegeo ASSERT: /buildAgent/work/d7fbe78406a06eb1/platform/Fonts/FontLoader.cpp (31) Failed to load Font file: FrankBold50_A8_icons.fnt

**Comment by scottmurray** [comment]
Hi umairnow, thank you for reporting this issue. 

In general, the SDK streams resources (like map tiles, textures, etc.) over the network on-demand as required. However, the SDK does expect a small number of resources to be embedded into the app, like fonts and placeholder textures. It looks like one of these font files are missing (https://github.com/eegeo/ios-api-example/blob/master/Resources/FrankBold50_A8_icons.fnt).

Can you confirm that if you have set up your own new project, you have added resources in the same way as the example project? If you are using the provided eeGeoApiExample.xcodeproj, can you confirm that the files in the Resources directory are being found by Xcode, and embedded into the app?

**Comment by umairnow** [comment]
Thanks, I have added all the assets which example application have and it is running without crash. But I am unable to understand that why those assets are not included in the library if they are mandatory for library.

**Comment by scottmurray** [comment]
Thanks for the feedback. We distribute the data with the project rather than with the SDK libraries and headers so that users can change the data to suit their needs if required. 

We are intending to automate the generation of the Xcode project files using CMake in future which should help avoid issues like this when generating custom projects.
